name: Build SunamoPercentCalculator

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build SunamoPercentCalculator
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoPercentCalculator/SunamoPercentCalculator.csproj

    - name: Build
      run: dotnet build SunamoPercentCalculator/SunamoPercentCalculator.csproj --configuration Release --no-restore

  test:
    name: Test SunamoPercentCalculator.Tests
    runs-on: ${{ matrix.os }}
    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoPercentCalculator.Tests/SunamoPercentCalculator.Tests.csproj

    - name: Build tests
      run: dotnet build SunamoPercentCalculator.Tests/SunamoPercentCalculator.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test SunamoPercentCalculator.Tests/SunamoPercentCalculator.Tests.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
